config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :products
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'categories#index'

  match '/contact', to: 'categories#contact', via: :get
  match '/home', to: 'categories#home', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
  mount_uploader :logo, LogoUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    render :index
  end

  def show
    @category = Category.find(params[:id])
    render :show
  end

  def new
    @category = Category.new
    render :new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    render :edit
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :logo)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    render :index
  end

  def show
    @category = Category.find(params[:category_id])
    @product = @category.products.find(params[:id])
    render :show
  end

  def new
    @category = Category.find(params[:category_id])
    @product = @category.products.new
  end

  def create
    @category = Category.find(params[:category_id])
    @product = @category.products.new(product_params)
    if @product.save
      redirect_to category_path(@product.category)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :detail, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= render 'layouts/errors', :object => @category %>

<%= form_for @category, :html => {:multipart => true} do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.file_field :logo %>
<%= f.submit %>
<% end %>

app/views/categories/contact.html.erb
contact

app/views/categories/edit.html.erb
<h3>Update the category.</h3>

<%= render 'form' %>

app/views/categories/home.html.erb
homepage.

app/views/categories/index.html.erb
<h1>CATEGORIES.</h1>

<ul>
  <% @categories.each do |category| %>
    <div class="col-md-4 portfolio-item">
      <p>
        <img src="<%= category.logo %>" alt="<%= category.name %>" width="20%" height="30%">
      </p>
      <h3>
        <li style="font-size: 20px">
          <strong><%= link_to category.name, category_path(category) %></strong>
        </li>
      </h3>
    </div>

  <% end %>
</ul>

<br>
<h2>Add a category.</h2>
<%= link_to "New Category", new_category_path %>

app/views/categories/new.html.erb
<h3>Create a new category.</h3>

<%= render 'form' %>

app/views/categories/show.html.erb
<h2>Welcome to
  <%= @category.name %>
</h2>
<p><%= link_to "Edit", edit_category_path(@category) %>|
  <%= link_to "Delete", category_path(@category), :data => {:confirm => "Are you sure you want to DELETE this category??", :method => "delete"} %>|
</p>

<%= link_to "Add a product", new_category_product_path(@category) %>

<% if @category.products.any? %>
  <ul style="text-decoration: none;">
    <% @category.products.each do |product| %>
      <li style="text-decoration: none;">
        <%= link_to product.name, category_product_path(@category, product) %><br>
        <%= link_to "Edit", edit_category_product_path(@category, product) %>
        |
        <%= link_to "Delete", category_product_path(@category, product), :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet!</p>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>An error was encountered please try again.</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="w3-bar w3-black ">
      <a href="/home" class="w3-bar-item w3-button w3-mobile">Home</a>
      <a href="/" class="w3-bar-item w3-button w3-mobile">SHOP</a>
      <a href="/contact" class="w3-bar-item w3-button w3-mobile">CONTACT US</a>
    </div>
    <div class="w3-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render 'layouts/errors', :object => @product %>

<div class="form  column">
  <%= form_for [@category, @product] do |f| %>
  <div class="col-md-6">

    <div class="name">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
    </div>

    <div class="detail">
      <%= f.label :detail %>
      <br>
      <%= f.text_field :detail %>
    </div>

    <div class="price">
      <%= f.label :price %>
      <br>
      <%= f.text_field :price %>
    </div>

    <div class="image">
      <%= f.file_field :image %>
    </div>

    <div class="button">
      <%= f.submit %>
    </div>

  </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h3>Update Details for Product.</h3>

<%= render 'form' %>

app/views/products/new.html.erb
<h3>Fill in the Product details.</h3>

<%= render 'form' %>

app/views/products/show.html.erb
<p style="font-size: 40px; font: bold;">These are Details for <%= @product.name %>.</p>

<div class="container">
  <img style="width= 50px; height= 100px;"class="img-rounded" <%= image_tag @product.image_url.to_s %>
</div>

<hr>

<ul>
  <li> <strong>Details :-</strong> <%= @product.detail %></li><br>
  <li> <strong>price :-</strong> <%= @product.price %></li><br>
</ul>